[package]
name    = "rmail-storage"
version.workspace = true
edition.workspace = true

[dependencies]
rmail-config = { path = "../config" }
aws-config   = { version = "1", default-features = false, features = ["behavior-version-latest", "rt-tokio"] }
aws-credential-types = "1"
aws-sdk-s3   = { version = "1", default-features = false, features = ["behavior-version-latest", "rt-tokio", "rustls"] }
aws-smithy-types = "1"
bytes        = { workspace = true }
thiserror    = { workspace = true }
tracing      = { workspace = true }
