[package]
name    = "rmail-tls"
version.workspace = true
edition.workspace = true

[dependencies]
rmail-config   = { path = "../config" }
tokio          = { workspace = true }
tokio-rustls   = { workspace = true }
rustls         = { workspace = true }
rustls-pemfile = { workspace = true }
webpki-roots   = "0.26"
tracing        = { workspace = true }
thiserror      = { workspace = true }
