[package]
name    = "rmail-server"
version.workspace = true
edition.workspace = true

[dependencies]
rmail-core    = { path = "../core" }
rmail-config  = { path = "../config" }
rmail-queue   = { path = "../queue" }
rmail-mailbox = { path = "../mailbox" }
rmail-smtp    = { path = "../smtp" }
rmail-imap    = { path = "../imap" }
rmail-dns     = { path = "../dns" }
rmail-tls     = { path = "../tls" }
rmail-auth    = { path = "../auth" }
tokio         = { workspace = true }
tokio-rustls  = { workspace = true }
tracing       = { workspace = true }
thiserror     = { workspace = true }
anyhow        = { workspace = true }
time          = { workspace = true }
